embed_dir: /data/experiments/reptaxonomy/embeddings
out_dir: /data/experiments/reptaxonomy/outputs
seed: 42

dataset:
  dataset_name: ben_ge
  num_classes: 19
  ignore_index: 255

model_names:
  - clay_v1
  - satmae_large
  - prithvi_100m

projections:
  - umap
  - tsne
  - pca

representation: geo_euc
label_file_subset: 2000

test_batch_size: 1
test_num_workers: 4

